const VERSION='0.2.2', STORAGE_KEY='onlybeats.settings.v2', FAVORITES_KEY='onlybeats.favorites.v1';
const defaultSettings={theme:'dark',startPage:'dashboard',compact:false,sounds:false,animations:true,refresh:'30',favoriteTeam:''};
let settings=load(STORAGE_KEY,defaultSettings), favorites=load(FAVORITES_KEY,[]), currentPage=settings.startPage||'dashboard', games=[], loading=false, lastSync=null, syncError='', refreshTimer;
const pages=[['dashboard','⌂','Dashboard'],['live','◉','Live Games'],['schedule','▦','Schedule'],['favorites','★','Favorites'],['teams','◈','Team Hub'],['rankings','♛','Rankings'],['news','▤','News'],['weather','☁','Weather'],['availability','♙','Player Availability'],['predictions','✓','Predictions'],['reports','▥','Reports'],['developer','⌘','Developer Tools'],['settings','⚙','Settings']];
function load(k,d){try{const raw=localStorage.getItem(k);if(!raw)return Array.isArray(d)?[...d]:{...d};const parsed=JSON.parse(raw);return Array.isArray(d)?(Array.isArray(parsed)?parsed:[...d]):{...d,...parsed}}catch{return Array.isArray(d)?[...d]:{...d}}}
function saveSettings(){localStorage.setItem(STORAGE_KEY,JSON.stringify(settings));$('lastSaved').textContent='Saved just now';toast('Preferences saved');scheduleRefresh()}
function saveFavorites(){localStorage.setItem(FAVORITES_KEY,JSON.stringify(favorites));renderPage()}
function $(id){return document.getElementById(id)}
function applyTheme(){document.documentElement.dataset.theme=settings.theme}
function toast(m){const e=$('toast');e.textContent=m;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),2200)}
function renderNav(){$('nav').innerHTML=pages.map(([id,i,l])=>`<button class="nav-button ${id===currentPage?'active':''}" data-page="${id}"><span class="nav-icon">${i}</span>${l}</button>`).join('');document.querySelectorAll('.nav-button').forEach(b=>b.onclick=()=>navigate(b.dataset.page))}
function navigate(p){currentPage=p;renderNav();renderPage()}
function setHeading(t,e='ONLYBEATS COMMAND CENTER'){$('sectionTitle').textContent=t;$('sectionEyebrow').textContent=e}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function metric(l,v,s){return `<div class="metric"><span>${l}</span><strong>${v}</strong><small>${s}</small></div>`}
function card(t,b,c=''){return `<article class="card ${c}"><div class="card-head"><h3>${t}</h3></div>${b}</article>`}
function empty(t,c){return `<div class="empty-state"><div><strong>${t}</strong><p>${c}</p></div></div>`}
function normalize(data){return (data.events||[]).map(e=>{const c=e.competitions?.[0]||{}, comps=c.competitors||[], home=comps.find(x=>x.homeAway==='home')||comps[0]||{}, away=comps.find(x=>x.homeAway==='away')||comps[1]||{}, state=e.status?.type?.state||'pre';return {id:e.id,name:e.name||'',date:e.date,status:e.status?.type?.shortDetail||e.status?.type?.detail||'Scheduled',state,clock:e.status?.displayClock||'',period:e.status?.period||0,network:c.broadcasts?.[0]?.names?.[0]||'',venue:c.venue?.fullName||'',home:team(home),away:team(away)}})}
function team(c){return {name:c.team?.displayName||'TBD',abbr:c.team?.abbreviation||'',logo:c.team?.logo||'',score:c.score||'0',rank:c.curatedRank?.current&&c.curatedRank.current<99?c.curatedRank.current:null,record:c.records?.[0]?.summary||''}}
function updateProviderStatus(ok){const status=$('providerStatus'),dot=$('providerDot');if(status)status.textContent=ok?'Score provider online':'Score provider unavailable';if(dot)dot.className=ok?'status-dot':'status-dot error'}
async function syncScores(silent=false){if(loading)return;loading=true;syncError='';if(!silent)renderPage();try{let data;if(window.__TAURI__?.core?.invoke)data=await window.__TAURI__.core.invoke('fetch_scoreboard');else{const r=await fetch('https://site.api.espn.com/apis/site/v2/sports/football/college-football/scoreboard?limit=200');if(!r.ok)throw new Error(`HTTP ${r.status}`);data=await r.json()}games=normalize(data);lastSync=new Date();updateProviderStatus(true)}catch(e){syncError=String(e?.message||e);updateProviderStatus(false);if(!silent)toast('Could not refresh live scores')}finally{loading=false;renderPage()}}
function scheduleRefresh(){clearInterval(refreshTimer);refreshTimer=setInterval(()=>syncScores(true),Number(settings.refresh||30)*1000)}
function gameCard(g){const fav=favorites.includes(g.home.abbr)||favorites.includes(g.away.abbr);return `<button class="game-card ${g.state==='in'?'live-game':''}" data-game="${g.id}"><div class="game-meta"><span class="pill ${g.state==='in'?'live-pill':''}">${esc(g.status)}</span><span>${esc(g.network||g.venue||'')}</span></div>${teamRow(g.away)}${teamRow(g.home)}<div class="game-footer"><span>${new Date(g.date).toLocaleString([],{weekday:'short',hour:'numeric',minute:'2-digit'})}</span><span>${fav?'★ Favorite matchup':'View details →'}</span></div></button>`}
function teamRow(t){return `<div class="team-row">${t.logo?`<img src="${esc(t.logo)}" alt="">`:'<span class="team-fallback">🏈</span>'}<strong>${t.rank?`<small>${t.rank}</small> `:''}${esc(t.name)}</strong><span>${esc(t.record)}</span><b>${esc(t.score)}</b></div>`}
function filteredGames(){const q=($('gameSearch')?.value||'').toLowerCase();return games.filter(g=>!q||g.name.toLowerCase().includes(q)||g.home.name.toLowerCase().includes(q)||g.away.name.toLowerCase().includes(q))}
function dashboard(){setHeading('Dashboard');const live=games.filter(g=>g.state==='in'),up=games.filter(g=>g.state==='pre'),finals=games.filter(g=>g.state==='post');return `<div class="hero"><div class="hero-copy"><p class="eyebrow">RELEASE 0.2 LIVE FOOTBALL</p><h2>Your Saturday command center is online.</h2><p>Live NCAA scores, game status, favorites, search, automatic refresh, and provider diagnostics are now connected.</p></div><img src="assets/onlybeats-icon.png" alt="OnlyBeats logo"></div><div class="metric-grid">${metric('Live Games',live.length,lastSync?'Updated '+lastSync.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'Not synced')}${metric('Upcoming',up.length,'Current scoreboard')}${metric('Final',finals.length,'Current scoreboard')}${metric('Favorites',favorites.length,'Saved locally')}</div><div class="dashboard-grid">${card('Live Game Center',loading?empty('Refreshing scores…','Connecting to the live scoreboard.'):syncError?errorBox():games.length?`<div class="mini-games">${games.slice(0,4).map(gameCard).join('')}</div>`:empty('No games on the current slate','The provider is online, but no current games were returned.'),'wide')}${card('Favorite Teams',favorites.length?`<div class="favorite-list">${favorites.map(x=>`<span class="favorite-chip">★ ${esc(x)}</span>`).join('')}</div>`:empty('No favorites yet','Open Live Games and star a team.'))}${card('System Health',healthPanel())}${card('Upcoming Kickoffs',up.length?up.slice(0,5).map(g=>`<div class="compact-game"><strong>${esc(g.away.abbr)} at ${esc(g.home.abbr)}</strong><span>${new Date(g.date).toLocaleString([],{weekday:'short',hour:'numeric',minute:'2-digit'})}</span></div>`).join(''):empty('No upcoming games','Refresh when a new slate is published.'))}</div>`}
function livePage(){setHeading('Live Games','REAL-TIME SCOREBOARD');return `<div class="toolbar"><input id="gameSearch" placeholder="Search teams or matchups…"><button class="button primary" id="refreshScores">${loading?'Refreshing…':'Refresh now'}</button><span class="muted">Auto-refresh: ${settings.refresh}s</span></div>${syncError?errorBox():''}<div class="games-grid">${loading&&!games.length?empty('Loading live scoreboard…','This can take a few seconds on the first request.'):filteredGames().map(gameCard).join('')||empty('No matching games','Try another team name or refresh the scoreboard.')}</div>`}
function errorBox(){return `<div class="error-box"><strong>Live scores unavailable</strong><p>${esc(syncError)}</p><button class="button" onclick="syncScores()">Try again</button></div>`}
function favoritesPage(){setHeading('Favorites','YOUR TEAMS');const related=games.filter(g=>favorites.includes(g.home.abbr)||favorites.includes(g.away.abbr));return `<div class="card"><h3>Favorite teams</h3><p class="muted">Favorites are stored locally on this computer.</p><div class="favorite-list">${favorites.map(x=>`<button class="favorite-chip removable" data-remove="${esc(x)}">★ ${esc(x)} ×</button>`).join('')||'<span class="muted">No teams saved yet.</span>'}</div></div><div class="games-grid">${related.map(gameCard).join('')||empty('No favorite-team games on this slate','Add favorites from any game details panel.')}</div>`}
function healthPanel(){return `<div class="health-list"><div><i id="providerDot" class="status-dot ${syncError?'error':''}"></i><span id="providerStatus">${syncError?'Score provider unavailable':'Score provider online'}</span></div><div><i class="status-dot"></i><span>Local settings ready</span></div><div><i class="status-dot"></i><span>SQLite schema 1</span></div><div><i class="status-dot"></i><span>Build ${VERSION}</span></div></div>`}
function developerPage(){setHeading('Developer Tools','DIAGNOSTICS');return `<div class="settings-layout">${card('System Health',healthPanel())}${card('Sync Information',`<div class="detail-list"><div><span>Last sync</span><strong>${lastSync?lastSync.toLocaleString():'Not yet'}</strong></div><div><span>Games cached</span><strong>${games.length}</strong></div><div><span>Refresh interval</span><strong>${settings.refresh} seconds</strong></div><div><span>Runtime</span><strong>${window.__TAURI__?'Tauri desktop':'Browser preview'}</strong></div></div>`)}${card('Troubleshooting',`<p class="muted">Use Refresh now first. If the provider remains offline, confirm your internet connection and open TROUBLESHOOTING.md.</p><button class="button primary" onclick="syncScores()">Run provider test</button>`)}${card('Version',`<div class="detail-list"><div><span>Application</span><strong>${VERSION}</strong></div><div><span>Database schema</span><strong>1</strong></div><div><span>Score provider</span><strong>ESPN scoreboard</strong></div></div>`)}</div>`}
function placeholderPage(id,label){setHeading(label,'COMING IN A PLANNED RELEASE');return `<div class="hero"><div class="hero-copy"><p class="eyebrow">ROADMAP MODULE</p><h2>${label}</h2><p>This route is prepared and will receive its complete data module in a future release.</p></div><img src="assets/onlybeats-icon.png"></div>`}
function toggle(id,label,on){return `<div class="toggle-row"><div><strong>${label}</strong></div><button id="${id}" class="toggle ${on?'on':''}"></button></div>`}
function settingsPage(){setHeading('Settings','LOCAL PREFERENCES');return `<div class="settings-layout"><section class="card settings-card"><h3>Appearance</h3><div class="field"><label>Theme</label><select id="themeSelect"><option value="dark">Dark Command Center</option><option value="light">Light</option></select></div>${toggle('compactToggle','Compact dashboard cards',settings.compact)}${toggle('animationToggle','Interface animations',settings.animations)}</section><section class="card settings-card"><h3>Live scores</h3><div class="field"><label>Automatic refresh</label><select id="refreshSelect"><option value="15">15 seconds</option><option value="30">30 seconds</option><option value="60">60 seconds</option></select></div><button class="button primary" id="testProvider">Test live-score provider</button></section><section class="card settings-card"><h3>Startup</h3><div class="field"><label>Start page</label><select id="startPageSelect">${pages.map(([id,,l])=>`<option value="${id}">${l}</option>`).join('')}</select></div></section><section class="card settings-card"><h3>Data & recovery</h3><div class="button-row"><button id="exportButton" class="button primary">Export settings</button><button id="resetButton" class="button danger">Reset settings</button></div><p class="muted">App ${VERSION} · Database schema 1</p></section></div>`}
function renderPage(){const label=pages.find(p=>p[0]===currentPage)?.[2]||'Module';$('content').innerHTML=currentPage==='dashboard'?dashboard():currentPage==='live'?livePage():currentPage==='favorites'?favoritesPage():currentPage==='developer'?developerPage():currentPage==='settings'?settingsPage():placeholderPage(currentPage,label);bindPage()}
function bindPage(){document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>showGame(b.dataset.game));if($('refreshScores'))$('refreshScores').onclick=()=>syncScores();if($('gameSearch'))$('gameSearch').oninput=()=>{document.querySelector('.games-grid').innerHTML=filteredGames().map(gameCard).join('')||empty('No matching games','Try another team name.') ;bindPage()};document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{favorites=favorites.filter(x=>x!==b.dataset.remove);saveFavorites()});if(currentPage==='settings')bindSettings()}
function showGame(id){const g=games.find(x=>x.id===id);if(!g)return;const choices=[g.away,g.home];$('gameModalBody').innerHTML=`<div class="modal-game"><p class="eyebrow">${esc(g.status)}</p><h2>${esc(g.away.name)} at ${esc(g.home.name)}</h2><div class="score-display"><span>${esc(g.away.abbr)} <b>${esc(g.away.score)}</b></span><span>${esc(g.home.abbr)} <b>${esc(g.home.score)}</b></span></div><p>${esc(g.network||'Network not listed')} · ${esc(g.venue||'Venue not listed')}</p><div class="button-row">${choices.map(t=>`<button class="button ${favorites.includes(t.abbr)?'primary':''}" data-favorite="${esc(t.abbr)}">${favorites.includes(t.abbr)?'★ Remove':'☆ Add'} ${esc(t.name)}</button>`).join('')}</div></div>`;$('gameModal').classList.remove('hidden');document.querySelectorAll('[data-favorite]').forEach(b=>b.onclick=()=>{const a=b.dataset.favorite;favorites=favorites.includes(a)?favorites.filter(x=>x!==a):[...favorites,a];localStorage.setItem(FAVORITES_KEY,JSON.stringify(favorites));showGame(id);renderPage()})}
function bindSettings(){const t=$('themeSelect');t.value=settings.theme;t.onchange=()=>{settings.theme=t.value;applyTheme();saveSettings()};const r=$('refreshSelect');r.value=settings.refresh;r.onchange=()=>{settings.refresh=r.value;saveSettings()};const s=$('startPageSelect');s.value=settings.startPage;s.onchange=()=>{settings.startPage=s.value;saveSettings()};[['compactToggle','compact'],['animationToggle','animations']].forEach(([id,k])=>$(id).onclick=e=>{settings[k]=!settings[k];e.currentTarget.classList.toggle('on',settings[k]);saveSettings()});$('testProvider').onclick=()=>syncScores();$('exportButton').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({settings,favorites},null,2)],{type:'application/json'}));a.download='OnlyBeats-settings-v0.2.2.json';a.click();toast('Settings export created')};$('resetButton').onclick=()=>{if(confirm('Reset preferences and favorites?')){settings={...defaultSettings};favorites=[];localStorage.clear();applyTheme();renderPage()}}}
const palette=$('commandPalette'),input=$('commandInput'),results=$('commandResults');function openPalette(){palette.classList.remove('hidden');input.value='';renderCommands('');setTimeout(()=>input.focus(),0)}function closePalette(){palette.classList.add('hidden')}function renderCommands(q){results.innerHTML=pages.filter(p=>p[2].toLowerCase().includes(q.toLowerCase())).map(([id,i,l])=>`<button class="command-result" data-page="${id}"><span>${i} ${l}</span><small>Open page</small></button>`).join('');results.querySelectorAll('button').forEach(b=>b.onclick=()=>{navigate(b.dataset.page);closePalette()})}
$('commandButton').onclick=openPalette;palette.onclick=e=>{if(e.target===palette)closePalette()};input.oninput=()=>renderCommands(input.value);$('closeGameModal').onclick=()=>$('gameModal').classList.add('hidden');$('gameModal').onclick=e=>{if(e.target.id==='gameModal')$('gameModal').classList.add('hidden')};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openPalette()}if(e.key==='Escape'){closePalette();$('gameModal').classList.add('hidden')}});$('themeButton').onclick=()=>{settings.theme=settings.theme==='dark'?'light':'dark';applyTheme();saveSettings()};$('notificationButton').onclick=()=>toast('Live alerts arrive in a future release');setInterval(()=>$('clock').textContent=new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),1000);
applyTheme();renderNav();renderPage();scheduleRefresh();setTimeout(()=>$('splash').classList.add('hide'),1200);syncScores(true);
