const VERSION='0.6.0';
const STORAGE_KEY='onlybeats.settings.v6';
const LEGACY_STORAGE_KEY='onlybeats.settings.v5';
const FAVORITES_KEY='onlybeats.favorites.v1';
const WALL_KEY='onlybeats.wall.v1';
const defaultSettings={theme:'dark',startPage:'wall',compact:false,sounds:false,animations:true,refresh:'30',favoriteTeam:'',scoreAlerts:true,favoriteAlerts:true,kickoffAlerts:true,weatherLocation:''};
const defaultWall={status:'all',favoritesOnly:false,top25Only:false,query:''};
let settings=loadSettings();
let favorites=load(FAVORITES_KEY,[]);
let wallState=load(WALL_KEY,defaultWall);
let currentPage=settings.startPage||'wall';
let games=[];
let loading=false;
let lastSync=null;
let syncError='';
let refreshTimer;
let previousScores=new Map();
let changedGames=new Set();
let activeGameId=null;
let activeTeamAbbr='';
let teamTab='overview';
let teamQuery='';
let weatherData=null;
let weatherLoading=false;
let weatherError='';
let notificationHistory=[];
let focusedGameId=null;
const pages=[['dashboard','⌂','Dashboard'],['wall','▦','Saturday Wall'],['schedule','◷','Schedule'],['favorites','★','Favorites'],['teams','◈','Team Hub'],['rankings','♛','Rankings'],['news','▤','News'],['weather','☁','Weather'],['availability','♙','Player Availability'],['predictions','✓','Predictions'],['reports','▥','Reports'],['developer','⌘','Developer Tools'],['settings','⚙','Settings']];

function load(k,d){try{const raw=localStorage.getItem(k);if(!raw)return Array.isArray(d)?[...d]:{...d};const parsed=JSON.parse(raw);return Array.isArray(d)?(Array.isArray(parsed)?parsed:[...d]):{...d,...parsed}}catch{return Array.isArray(d)?[...d]:{...d}}}
function loadSettings(){const current=localStorage.getItem(STORAGE_KEY);if(current)return load(STORAGE_KEY,defaultSettings);const legacy=localStorage.getItem(LEGACY_STORAGE_KEY);if(legacy){try{const migrated={...defaultSettings,...JSON.parse(legacy),startPage:'wall'};localStorage.setItem(STORAGE_KEY,JSON.stringify(migrated));return migrated}catch{}}return {...defaultSettings}}
function saveSettings(showToast=true){localStorage.setItem(STORAGE_KEY,JSON.stringify(settings));const saved=$('lastSaved');if(saved)saved.textContent='Saved just now';if(showToast)toast('Preferences saved');scheduleRefresh()}
function saveFavorites(){localStorage.setItem(FAVORITES_KEY,JSON.stringify(favorites));renderPage()}
function saveWall(){localStorage.setItem(WALL_KEY,JSON.stringify(wallState))}
function $(id){return document.getElementById(id)}
function applyTheme(){document.documentElement.dataset.theme=settings.theme;document.body.classList.toggle('compact-mode',Boolean(settings.compact));document.body.classList.toggle('reduce-motion',!settings.animations)}
function toast(message,tone='default'){const e=$('toast');if(!e)return;e.textContent=message;e.dataset.tone=tone;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),2600)}
function renderNav(){$('nav').innerHTML=pages.map(([id,i,l])=>`<button class="nav-button ${id===currentPage?'active':''}" data-page="${id}"><span class="nav-icon">${i}</span>${l}</button>`).join('');document.querySelectorAll('.nav-button').forEach(b=>b.onclick=()=>navigate(b.dataset.page))}
function navigate(page){currentPage=page;renderNav();renderPage()}
function setHeading(title,eyebrow='ONLYBEATS COMMAND CENTER'){$('sectionTitle').textContent=title;$('sectionEyebrow').textContent=eyebrow}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function metric(label,value,sub){return `<div class="metric"><span>${label}</span><strong>${value}</strong><small>${sub}</small></div>`}
function card(title,body,cls=''){return `<article class="card ${cls}"><div class="card-head"><h3>${title}</h3></div>${body}</article>`}
function empty(title,copy){return `<div class="empty-state"><div><strong>${title}</strong><p>${copy}</p></div></div>`}
function normalize(data){return (data.events||[]).map(e=>{const c=e.competitions?.[0]||{},comps=c.competitors||[],home=comps.find(x=>x.homeAway==='home')||comps[0]||{},away=comps.find(x=>x.homeAway==='away')||comps[1]||{},state=e.status?.type?.state||'pre';return {id:e.id,name:e.name||'',date:e.date,status:e.status?.type?.shortDetail||e.status?.type?.detail||'Scheduled',state,clock:e.status?.displayClock||'',period:e.status?.period||0,network:c.broadcasts?.[0]?.names?.[0]||'',venue:c.venue?.fullName||'',city:c.venue?.address?.city||'',stateCode:c.venue?.address?.state||'',neutral:Boolean(c.neutralSite),home:team(home),away:team(away)}})}
function team(c){return {id:c.team?.id||'',name:c.team?.displayName||'TBD',shortName:c.team?.shortDisplayName||c.team?.displayName||'TBD',abbr:c.team?.abbreviation||'',logo:c.team?.logo||'',score:Number(c.score||0),rank:c.curatedRank?.current&&c.curatedRank.current<99?c.curatedRank.current:null,record:c.records?.[0]?.summary||'',winner:Boolean(c.winner)}}
function updateProviderStatus(ok){const status=$('providerStatus'),dot=$('providerDot');if(status)status.textContent=ok?'Score provider online':'Score provider unavailable';if(dot)dot.className=ok?'status-dot':'status-dot error'}
function captureChanges(nextGames){const nextChanged=new Set();for(const g of nextGames){const before=previousScores.get(g.id);const current=`${g.away.score}-${g.home.score}-${g.state}-${g.period}-${g.clock}`;if(before&&before!==current){nextChanged.add(g.id);if(g.away.score+g.home.score>Number(before.split('-')[0])+Number(before.split('-')[1]))announceScoreChange(g)}previousScores.set(g.id,current)}changedGames=nextChanged;if(changedGames.size)setTimeout(()=>{changedGames.clear();document.querySelectorAll('.score-changed').forEach(e=>e.classList.remove('score-changed'))},4200)}
function announceScoreChange(g){const leader=g.away.score>g.home.score?g.away:g.home.score>g.away.score?g.home:null;const message=leader?`${leader.shortName} leads ${Math.max(g.away.score,g.home.score)}–${Math.min(g.away.score,g.home.score)}`:`${g.away.shortName} and ${g.home.shortName} are tied`;showAlert('SCORE UPDATE',message,g)}
function showAlert(title,message,g){if(!settings.scoreAlerts)return;notificationHistory.unshift({title,message,time:new Date().toISOString(),gameId:g?.id||''});notificationHistory=notificationHistory.slice(0,30);localStorage.setItem('onlybeats.notifications.v1',JSON.stringify(notificationHistory));const host=$('alertStack');if(!host)return;const item=document.createElement('button');item.className='game-alert';item.innerHTML=`<span>⚡</span><div><small>${esc(title)}</small><strong>${esc(message)}</strong></div>`;item.onclick=()=>{showGame(g.id);item.remove()};host.prepend(item);setTimeout(()=>item.remove(),6500)}
async function syncScores(silent=false){if(loading)return;loading=true;syncError='';if(!silent)renderPage();try{let data;if(window.__TAURI__?.core?.invoke)data=await window.__TAURI__.core.invoke('fetch_scoreboard');else{const r=await fetch('https://site.api.espn.com/apis/site/v2/sports/football/college-football/scoreboard?limit=200');if(!r.ok)throw new Error(`HTTP ${r.status}`);data=await r.json()}const next=normalize(data);captureChanges(next);games=next;lastSync=new Date();updateProviderStatus(true)}catch(e){syncError=String(e?.message||e);updateProviderStatus(false);if(!silent)toast('Could not refresh live scores','error')}finally{loading=false;renderPage();if(activeGameId&&games.some(g=>g.id===activeGameId))showGame(activeGameId,false)}}
function scheduleRefresh(){clearInterval(refreshTimer);const seconds=Number(settings.refresh||30);if(seconds>0)refreshTimer=setInterval(()=>syncScores(true),seconds*1000)}
function isFavoriteGame(g){return favorites.includes(g.home.abbr)||favorites.includes(g.away.abbr)}
function isTop25(g){return Boolean(g.home.rank||g.away.rank)}
function sortGames(list){return [...list].sort((a,b)=>{const fav=Number(isFavoriteGame(b))-Number(isFavoriteGame(a));if(fav)return fav;const live=Number(b.state==='in')-Number(a.state==='in');if(live)return live;const ranked=Number(isTop25(b))-Number(isTop25(a));if(ranked)return ranked;return new Date(a.date)-new Date(b.date)})}
function filteredWallGames(){const q=(wallState.query||'').toLowerCase().trim();return sortGames(games.filter(g=>{if(wallState.status!=='all'&&g.state!==wallState.status)return false;if(wallState.favoritesOnly&&!isFavoriteGame(g))return false;if(wallState.top25Only&&!isTop25(g))return false;if(q&&!`${g.name} ${g.home.name} ${g.away.name} ${g.home.abbr} ${g.away.abbr}`.toLowerCase().includes(q))return false;return true}))}
function statusLabel(state){return state==='in'?'LIVE':state==='post'?'FINAL':'UPCOMING'}
function kickoffText(g){const d=new Date(g.date);return g.state==='pre'?d.toLocaleString([],{weekday:'short',hour:'numeric',minute:'2-digit'}):g.status}
function logo(team){return team.logo?`<img src="${esc(team.logo)}" alt="${esc(team.name)} logo" loading="lazy">`:'<span class="team-fallback">🏈</span>'}
function teamLine(t){return `<div class="wall-team ${t.winner?'winner':''}">${logo(t)}<div class="wall-team-name"><strong>${t.rank?`<small>#${t.rank}</small> `:''}${esc(t.shortName)}</strong><span>${esc(t.record||t.abbr)}</span></div><b>${t.score}</b></div>`}
function gameCard(g){const fav=isFavoriteGame(g),changed=changedGames.has(g.id);return `<button class="wall-game-card state-${g.state} ${fav?'favorite-matchup':''} ${changed?'score-changed':''}" data-game="${g.id}"><div class="wall-card-top"><span class="status-badge state-${g.state}">${statusLabel(g.state)}</span><span>${esc(g.network||kickoffText(g))}</span><span class="favorite-mark">${fav?'★':''}</span></div><div class="wall-matchup">${teamLine(g.away)}${teamLine(g.home)}</div><div class="wall-card-bottom"><span>${esc(kickoffText(g))}</span><span>${esc(g.venue||'Venue TBD')}</span></div><span class="focus-link" data-focus="${g.id}">Focus</span></button>`}
function wallToolbar(){const buttons=[['all','All Games'],['in','Live'],['pre','Upcoming'],['post','Final']];return `<div class="wall-toolbar"><div class="wall-status-tabs">${buttons.map(([id,label])=>`<button class="filter-button ${wallState.status===id?'active':''}" data-status="${id}">${label}<span>${id==='all'?games.length:games.filter(g=>g.state===id).length}</span></button>`).join('')}</div><div class="wall-tools"><button class="filter-button ${wallState.favoritesOnly?'active':''}" id="favoritesFilter">★ Favorites</button><button class="filter-button ${wallState.top25Only?'active':''}" id="top25Filter">Top 25</button><input id="wallSearch" value="${esc(wallState.query)}" placeholder="Search teams…"><button class="button primary" id="refreshScores">${loading?'Refreshing…':'Refresh'}</button></div></div>`}
function dashboard(){setHeading('Dashboard');const live=games.filter(g=>g.state==='in'),up=games.filter(g=>g.state==='pre'),finals=games.filter(g=>g.state==='post');const featured=sortGames(games).slice(0,4);return `<div class="hero"><div class="hero-copy"><p class="eyebrow">RELEASE 0.5 INTELLIGENCE CENTER</p><h2>Your live football intelligence layer is online.</h2><p>Track ranked teams on the current slate, upset-watch games, favorite-team alerts, and provider health from one focused workspace.</p><button class="button primary hero-action" data-open-wall>Open Saturday Wall</button></div><img src="assets/onlybeats-icon.png" alt="OnlyBeats logo"></div><div class="metric-grid">${metric('Live Games',live.length,lastSync?'Updated '+lastSync.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'Not synced')}${metric('Upcoming',up.length,'Current slate')}${metric('Final',finals.length,'Current slate')}${metric('Favorites',favorites.length,'Pinned locally')}</div><div class="dashboard-grid">${card('Featured Matchups',loading?empty('Refreshing scores…','Connecting to the live scoreboard.'):syncError?errorBox():featured.length?`<div class="mini-wall">${featured.map(gameCard).join('')}</div>`:empty('No games on the current slate','The provider returned no current games.'),'wide')}${card('Favorite Teams',favorites.length?`<div class="favorite-list">${favorites.map(x=>`<span class="favorite-chip">★ ${esc(x)}</span>`).join('')}</div>`:empty('No favorites yet','Open a game and star a team.'))}${card('System Health',healthPanel())}${card('Upcoming Kickoffs',up.length?sortGames(up).slice(0,5).map(g=>`<div class="compact-game"><strong>${esc(g.away.abbr)} at ${esc(g.home.abbr)}</strong><span>${new Date(g.date).toLocaleString([],{weekday:'short',hour:'numeric',minute:'2-digit'})}</span></div>`).join(''):empty('No upcoming games','Refresh when a new slate is published.'))}</div>`}
function wallPage(){setHeading('Saturday Wall','GAME-DAY MISSION CONTROL');const list=filteredWallGames();return `<section class="wall-summary"><div><p class="eyebrow">LIVE BOARD</p><h2>${games.filter(g=>g.state==='in').length} live · ${games.filter(g=>g.state==='pre').length} upcoming · ${games.filter(g=>g.state==='post').length} final</h2></div><div class="sync-chip ${syncError?'error':''}"><i class="status-dot ${syncError?'error':''}"></i>${syncError?'Provider unavailable':lastSync?`Updated ${lastSync.toLocaleTimeString([],{hour:'numeric',minute:'2-digit',second:'2-digit'})}`:'Waiting for first sync'}</div></section>${wallToolbar()}${syncError?errorBox():''}<div class="wall-grid">${loading&&!games.length?empty('Loading Saturday Wall…','The first scoreboard request can take a few seconds.'):list.map(gameCard).join('')||empty('No games match these filters','Clear one or more filters or search for another team.')}</div>`}
function favoritesPage(){setHeading('Favorites','YOUR TEAMS');const related=sortGames(games.filter(isFavoriteGame));return `<div class="card"><h3>Favorite teams</h3><p class="muted">Favorites are stored locally and automatically pinned on Saturday Wall.</p><div class="favorite-list">${favorites.map(x=>`<button class="favorite-chip removable" data-remove="${esc(x)}">★ ${esc(x)} ×</button>`).join('')||'<span class="muted">No teams saved yet.</span>'}</div></div><div class="wall-grid favorites-wall">${related.map(gameCard).join('')||empty('No favorite-team games on this slate','Add favorites from any game details drawer.')}</div>`}
function errorBox(){return `<div class="error-box"><strong>Live scores unavailable</strong><p>${esc(syncError)}</p><button class="button" onclick="syncScores()">Try again</button></div>`}
function healthPanel(){return `<div class="health-list"><div><span><i id="providerDot" class="status-dot ${syncError?'error':''}"></i><span id="providerStatus">${syncError?'Score provider unavailable':'Score provider online'}</span></span><strong>${lastSync?'Synced':'Ready'}</strong></div><div><span><i class="status-dot"></i>Local settings</span><strong>Ready</strong></div><div><span><i class="status-dot"></i>SQLite schema</span><strong>1</strong></div><div><span><i class="status-dot"></i>Build</span><strong>${VERSION}</strong></div></div>`}
function developerPage(){setHeading('Developer Tools','DIAGNOSTICS');return `<div class="settings-layout">${card('System Health',healthPanel())}${card('Sync Information',`<div class="detail-list"><div><span>Last sync</span><strong>${lastSync?lastSync.toLocaleString():'Not yet'}</strong></div><div><span>Games cached</span><strong>${games.length}</strong></div><div><span>Live games</span><strong>${games.filter(g=>g.state==='in').length}</strong></div><div><span>Refresh interval</span><strong>${settings.refresh==='0'?'Off':settings.refresh+' seconds'}</strong></div><div><span>Runtime</span><strong>${window.__TAURI__?'Tauri desktop':'Browser preview'}</strong></div></div>`)}${card('Troubleshooting',`<p class="muted">Run the provider test first. If it remains offline, confirm internet access and review TROUBLESHOOTING.md.</p><button class="button primary" onclick="syncScores()">Run provider test</button>`)}${card('Version',`<div class="detail-list"><div><span>Application</span><strong>${VERSION}</strong></div><div><span>Database schema</span><strong>1</strong></div><div><span>Score provider</span><strong>ESPN scoreboard</strong></div><div><span>Intelligence layer</span><strong>Current-slate signals</strong></div><div><span>Saturday Wall filters</span><strong>Local</strong></div></div>`)}</div>`}

function allTeams(){const map=new Map();for(const g of games){for(const t of [g.away,g.home]){if(t.abbr&&!map.has(t.abbr))map.set(t.abbr,{...t,games:[]});map.get(t.abbr)?.games.push(g)}}return [...map.values()].sort((a,b)=>a.name.localeCompare(b.name))}
function selectedTeam(){const teams=allTeams();return teams.find(t=>t.abbr===activeTeamAbbr)||teams.find(t=>favorites.includes(t.abbr))||teams[0]||null}
function openTeam(abbr){activeTeamAbbr=abbr||'';teamTab='overview';currentPage='teams';renderNav();renderPage();closeGame()}
function teamRecordSnapshot(team){const related=games.filter(g=>g.home.abbr===team.abbr||g.away.abbr===team.abbr);let wins=0,losses=0,pending=0,pf=0,pa=0,finals=0;for(const g of related){const own=g.home.abbr===team.abbr?g.home:g.away,opp=g.home.abbr===team.abbr?g.away:g.home;if(g.state==='post'){finals++;pf+=own.score;pa+=opp.score;if(own.score>opp.score)wins++;else if(own.score<opp.score)losses++}else pending++}return {related,wins,losses,pending,pf,pa,finals}}
function teamDirectoryCard(t){const snap=teamRecordSnapshot(t);return `<button class="team-directory-card ${favorites.includes(t.abbr)?'favorite-team':''}" data-team="${esc(t.abbr)}">${logo(t)}<div><strong>${t.rank?`#${t.rank} `:''}${esc(t.name)}</strong><span>${esc(t.record||`${snap.wins}-${snap.losses}`||'Record unavailable')}</span></div><span class="team-card-arrow">›</span></button>`}
function teamHero(team){const fav=favorites.includes(team.abbr),snap=teamRecordSnapshot(team);return `<section class="team-hero">${logo(team)}<div class="team-hero-copy"><p class="eyebrow">TEAM HUB</p><h2>${team.rank?`<small>#${team.rank}</small> `:''}${esc(team.name)}</h2><p>${esc(team.record||`${snap.wins}-${snap.losses}`)} · ${snap.pending} game${snap.pending===1?'':'s'} pending on current slate</p></div><button class="button ${fav?'primary':''}" id="teamFavoriteButton">${fav?'★ Favorite':'☆ Add favorite'}</button></section>`}
function teamTabs(){return `<div class="team-tabs">${[['overview','Overview'],['schedule','Schedule'],['stats','Stats'],['roster','Roster']].map(([id,l])=>`<button class="${teamTab===id?'active':''}" data-team-tab="${id}">${l}</button>`).join('')}</div>`}
function teamOverview(team){const snap=teamRecordSnapshot(team),next=sortGames(snap.related.filter(g=>g.state!=='post'))[0],last=sortGames(snap.related.filter(g=>g.state==='post')).reverse()[0];return `<div class="team-content-grid">${card('Current Snapshot',`<div class="team-stat-grid"><div><span>Listed record</span><strong>${esc(team.record||'—')}</strong></div><div><span>Current rank</span><strong>${team.rank?`#${team.rank}`:'Unranked'}</strong></div><div><span>Slate games</span><strong>${snap.related.length}</strong></div><div><span>Favorite</span><strong>${favorites.includes(team.abbr)?'Yes':'No'}</strong></div></div>`,'wide')}${card('Next Game',next?`<button class="hub-game-link" data-game="${next.id}"><strong>${esc(next.away.abbr)} at ${esc(next.home.abbr)}</strong><span>${esc(kickoffText(next))}</span><small>${esc(next.network||next.venue||'Details available')}</small></button>`:empty('No upcoming game found','Refresh the scoreboard when the next slate is available.'))}${card('Latest Result',last?`<button class="hub-game-link" data-game="${last.id}"><strong>${esc(last.away.abbr)} ${last.away.score} · ${esc(last.home.abbr)} ${last.home.score}</strong><span>${esc(last.status)}</span></button>`:empty('No final result found','Final games from the current scoreboard slate appear here.'))}${card('Team Data Coverage',`<div class="coverage-list"><span><i class="status-dot"></i>Identity and logo</span><span><i class="status-dot"></i>Current scoreboard schedule</span><span><i class="status-dot"></i>Favorite status</span><span><i class="status-dot pending"></i>Full season roster provider planned</span></div>`,'wide')}</div>`}
function teamSchedule(team){const related=sortGames(teamRecordSnapshot(team).related);return `<div class="team-schedule-list">${related.map(g=>{const own=g.home.abbr===team.abbr?g.home:g.away,opp=g.home.abbr===team.abbr?g.away:g.home,site=g.home.abbr===team.abbr?'vs':'at';return `<button class="team-schedule-row" data-game="${g.id}"><span class="status-badge state-${g.state}">${statusLabel(g.state)}</span>${logo(opp)}<div><strong>${site} ${esc(opp.name)}</strong><small>${new Date(g.date).toLocaleString([],{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</small></div><b>${g.state==='pre'?esc(g.network||'TBD'):`${own.score}-${opp.score}`}</b></button>`}).join('')||empty('No schedule data yet','Refresh scores to load teams from the current slate.')}</div>`}
function teamStats(team){const s=teamRecordSnapshot(team),avgFor=s.finals?(s.pf/s.finals).toFixed(1):'—',avgAgainst=s.finals?(s.pa/s.finals).toFixed(1):'—';return `<div class="team-content-grid">${card('Current Slate Performance',`<div class="team-stat-grid"><div><span>Wins shown</span><strong>${s.wins}</strong></div><div><span>Losses shown</span><strong>${s.losses}</strong></div><div><span>Points/game</span><strong>${avgFor}</strong></div><div><span>Allowed/game</span><strong>${avgAgainst}</strong></div></div>`,'wide')}${card('Coverage Note',`<p class="muted">These statistics are calculated only from final games currently returned by the live scoreboard. Full-season offense, defense, and national-rank data will use a dedicated team-statistics provider in a later release.</p>`)}</div>`}
function teamRoster(team){return `<div class="card roster-ready"><div class="roster-icon">◈</div><h3>${esc(team.shortName)} roster integration</h3><p class="muted">The Team Hub structure is ready for player name, position, class, number, height, weight, and hometown data. No roster entries are shown until a reliable licensed or official provider is connected.</p><div class="coverage-list"><span><i class="status-dot"></i>Search and position filter UI planned</span><span><i class="status-dot"></i>Provider adapter location documented</span><span><i class="status-dot pending"></i>Live roster data not connected</span></div></div>`}
function teamHubPage(){setHeading('Team Hub','ALL TEAMS · ONE HOME');const teams=allTeams(),q=teamQuery.toLowerCase().trim(),visible=teams.filter(t=>!q||`${t.name} ${t.shortName} ${t.abbr}`.toLowerCase().includes(q)),team=selectedTeam();if(!team)return `<section class="wall-summary"><div><p class="eyebrow">TEAM DIRECTORY</p><h2>Load the live scoreboard to discover teams.</h2></div><button class="button primary" id="refreshScores">Refresh teams</button></section>${syncError?errorBox():empty('No teams loaded yet','Team Hub builds its directory from the current college-football scoreboard.')}`;if(!activeTeamAbbr)activeTeamAbbr=team.abbr;const body=teamTab==='schedule'?teamSchedule(team):teamTab==='stats'?teamStats(team):teamTab==='roster'?teamRoster(team):teamOverview(team);return `<div class="team-hub-layout"><aside class="team-directory"><div class="team-directory-head"><div><p class="eyebrow">TEAM DIRECTORY</p><strong>${teams.length} teams loaded</strong></div><input id="teamSearch" value="${esc(teamQuery)}" placeholder="Search teams…"></div><div class="team-directory-list">${visible.map(teamDirectoryCard).join('')||empty('No matching teams','Try a different name or abbreviation.')}</div></aside><section class="team-profile">${teamHero(team)}${teamTabs()}<div class="team-tab-body">${body}</div></section></div>`}

function rankedTeams(){return allTeams().filter(t=>t.rank).sort((a,b)=>a.rank-b.rank)}
function upsetWatchGames(){return sortGames(games.filter(g=>{if(g.state==='pre')return false;const ranked=g.away.rank?g.away:g.home.rank?g.home:null,other=ranked===g.away?g.home:g.away;if(!ranked)return false;return other.score>ranked.score||Boolean(other.winner)}))}
function favoriteIntel(){return sortGames(games.filter(isFavoriteGame)).map(g=>{const names=[g.away,g.home].filter(t=>favorites.includes(t.abbr)).map(t=>t.shortName).join(' & ');return {game:g,title:names||`${g.away.shortName} at ${g.home.shortName}`,copy:g.state==='in'?`${g.status} · ${g.away.score}-${g.home.score}`:g.state==='post'?`Final · ${g.away.score}-${g.home.score}`:`Kickoff ${new Date(g.date).toLocaleString([],{weekday:'short',hour:'numeric',minute:'2-digit'})}`}})}
function intelRow(icon,title,copy,g){return `<button class="intel-row" ${g?`data-game="${g.id}"`:''}><span class="intel-icon">${icon}</span><div><strong>${esc(title)}</strong><small>${esc(copy)}</small></div><b>›</b></button>`}
function rankingsPage(){setHeading('Intelligence Center','RANKINGS · ALERTS · GAME SIGNALS');const ranked=rankedTeams(),upsets=upsetWatchGames(),fav=favoriteIntel(),rankedGames=sortGames(games.filter(isTop25));return `<section class="intel-hero"><div><p class="eyebrow">CURRENT-SLATE INTELLIGENCE</p><h2>Know what matters before the next snap.</h2><p>Rankings shown here come directly from teams present on the loaded scoreboard. Full national polls and conference tables remain provider-ready until a licensed or reliable source is connected.</p></div><button class="button primary" id="refreshScores">${loading?'Refreshing…':'Refresh intelligence'}</button></section><div class="metric-grid">${metric('Ranked Teams',ranked.length,'On current slate')}${metric('Ranked Games',rankedGames.length,'Current scoreboard')}${metric('Upset Watch',upsets.length,'Live or final')}${metric('Favorite Alerts',fav.length,'Current slate')}</div>${syncError?errorBox():''}<div class="intelligence-grid">${card('Current-Slate Rankings',ranked.length?`<div class="ranking-list">${ranked.map(t=>`<button class="ranking-row" data-team="${esc(t.abbr)}"><span>${t.rank}</span>${logo(t)}<div><strong>${esc(t.shortName)}</strong><small>${esc(t.record||t.abbr)}</small></div><b>›</b></button>`).join('')}</div>`:empty('No ranked teams loaded','Refresh during an active college-football slate.'),'tall')}${card('Upset Watch',upsets.length?`<div class="intel-list">${upsets.map(g=>intelRow('⚠',`${g.away.shortName} ${g.away.score} · ${g.home.shortName} ${g.home.score}`,g.status,g)).join('')}</div>`:empty('No upset signals right now','Ranked teams are not currently trailing or losing.'),'tall')}${card('Favorite-Team Alerts',fav.length?`<div class="intel-list">${fav.map(x=>intelRow('★',x.title,x.copy,x.game)).join('')}</div>`:empty('No favorite alerts','Star teams from Saturday Wall or Team Hub.'),'tall')}${card('Ranked Matchups',rankedGames.length?`<div class="mini-wall">${rankedGames.slice(0,6).map(gameCard).join('')}</div>`:empty('No ranked matchups','The current scoreboard has no Top 25 teams.'),'wide')}${card('Provider Coverage',`<div class="provider-grid"><div><span class="status-dot"></span><strong>Live scores</strong><small>Connected</small></div><div><span class="status-dot"></span><strong>Scoreboard rankings</strong><small>Connected</small></div><div><span class="status-dot pending"></span><strong>Full polls</strong><small>Provider-ready</small></div><div><span class="status-dot pending"></span><strong>Conference standings</strong><small>Provider-ready</small></div><div><span class="status-dot pending"></span><strong>Editorial news</strong><small>Provider-ready</small></div><div><span class="status-dot pending"></span><strong>Player availability</strong><small>Licensed feed required</small></div></div>`,'wide')}</div>`}
function newsPage(){setHeading('Game Signals','LIVE INTELLIGENCE FEED');const live=sortGames(games.filter(g=>g.state==='in')),finals=sortGames(games.filter(g=>g.state==='post')).slice(0,10),upcoming=sortGames(games.filter(g=>g.state==='pre')).slice(0,10);return `<section class="intel-hero"><div><p class="eyebrow">SIGNAL FEED</p><h2>A factual feed built from the live scoreboard.</h2><p>This release does not fabricate headlines. It surfaces live state changes, finals, ranked matchups, and favorite-team activity while the editorial-news provider remains unconnected.</p></div><button class="button primary" id="refreshScores">Refresh feed</button></section><div class="signal-columns">${card('Live Now',live.length?`<div class="intel-list">${live.map(g=>intelRow('●',`${g.away.shortName} ${g.away.score} – ${g.home.score} ${g.home.shortName}`,g.status,g)).join('')}</div>`:empty('No live games','Live games will appear automatically.'))}${card('Recent Finals',finals.length?`<div class="intel-list">${finals.map(g=>intelRow('✓',`${g.away.shortName} ${g.away.score} – ${g.home.score} ${g.home.shortName}`,g.status,g)).join('')}</div>`:empty('No finals loaded','Completed games will appear here.'))}${card('Next Kickoffs',upcoming.length?`<div class="intel-list">${upcoming.map(g=>intelRow('◷',`${g.away.shortName} at ${g.home.shortName}`,new Date(g.date).toLocaleString([],{weekday:'short',hour:'numeric',minute:'2-digit'})+(g.network?` · ${g.network}`:''),g)).join('')}</div>`:empty('No upcoming games','Upcoming games will appear here.'))}</div><div class="card provider-notice"><div><p class="eyebrow">EDITORIAL NEWS</p><h3>News provider not connected yet</h3><p class="muted">The interface is ready for a licensed or approved news source. Until then, OnlyBeats shows verified scoreboard-derived signals instead of invented stories.</p></div><span class="provider-badge">PROVIDER-READY</span></div>`}

function weatherCodeLabel(code){const map={0:'Clear',1:'Mostly clear',2:'Partly cloudy',3:'Overcast',45:'Fog',48:'Freezing fog',51:'Light drizzle',53:'Drizzle',55:'Heavy drizzle',61:'Light rain',63:'Rain',65:'Heavy rain',71:'Light snow',73:'Snow',75:'Heavy snow',80:'Rain showers',81:'Showers',82:'Heavy showers',95:'Thunderstorms',96:'Storms with hail',99:'Severe storms'};return map[Number(code)]||'Conditions unavailable'}
function weatherIcon(code){code=Number(code);if(code===0)return '☀';if([1,2].includes(code))return '⛅';if([3,45,48].includes(code))return '☁';if([71,73,75].includes(code))return '❄';if(code>=95)return '⛈';return '🌧'}
async function fetchWeather(location){if(weatherLoading)return;weatherLoading=true;weatherError='';renderPage();try{if(!location)throw new Error('Enter a stadium city or location');let data;if(window.__TAURI__?.core?.invoke)data=await window.__TAURI__.core.invoke('fetch_weather',{input:{location}});else{const geo=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(location)}&count=1&language=en&format=json`).then(r=>r.json());const hit=geo.results?.[0];if(!hit)throw new Error('No weather location match found');data=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${hit.latitude}&longitude=${hit.longitude}&current=temperature_2m,apparent_temperature,precipitation,weather_code,wind_speed_10m,wind_gusts_10m&hourly=temperature_2m,precipitation_probability,weather_code,wind_speed_10m,wind_gusts_10m&temperature_unit=fahrenheit&wind_speed_unit=mph&precipitation_unit=inch&forecast_days=7&timezone=auto`).then(r=>r.json());data.resolved_location={name:hit.name,admin1:hit.admin1,country:hit.country}}weatherData=data;settings.weatherLocation=location;saveSettings(false);toast('Weather updated')}catch(e){weatherError=String(e?.message||e);toast('Weather unavailable','error')}finally{weatherLoading=false;renderPage()}}
function weatherPage(){setHeading('Weather Center','GAMEDAY CONDITIONS');const c=weatherData?.current,loc=weatherData?.resolved_location;const place=loc?[loc.name,loc.admin1].filter(Boolean).join(', '):settings.weatherLocation||'No location selected';const now=c?`<div class="weather-current"><span>${weatherIcon(c.weather_code)}</span><div><strong>${Math.round(c.temperature_2m)}°F</strong><p>${weatherCodeLabel(c.weather_code)}</p></div></div><div class="weather-metrics">${metric('Feels Like',`${Math.round(c.apparent_temperature)}°F`,'Current')}${metric('Wind',`${Math.round(c.wind_speed_10m)} mph`,'Sustained')}${metric('Gusts',`${Math.round(c.wind_gusts_10m)} mph`,'Current')}${metric('Precipitation',`${c.precipitation||0} in`,'Current hour')}</div>`:empty('Choose a stadium location','Enter a city and state to load current conditions and a seven-day hourly forecast.');return `<section class="intel-hero"><div><p class="eyebrow">OPEN-METEO WEATHER</p><h2>GameDay Weather Center</h2><p>Current conditions and stadium-area forecasts without invented data.</p></div><div class="weather-search"><input id="weatherLocation" value="${esc(settings.weatherLocation||'')}" placeholder="Stadium city, state"><button class="button primary" id="loadWeather">${weatherLoading?'Loading…':'Load weather'}</button></div></section>${weatherError?`<div class="error-banner">${esc(weatherError)}</div>`:''}<section class="card weather-card"><div class="card-head"><h3>${esc(place)}</h3><span class="provider-badge">LIVE PROVIDER</span></div>${now}</section>`}
function openFocus(id){const g=games.find(x=>x.id===id);if(!g)return;focusedGameId=id;$('focusBody').innerHTML=`<div class="focus-header"><p class="eyebrow">GAME FOCUS MODE</p><h2>${esc(g.away.shortName)} at ${esc(g.home.shortName)}</h2><p>${esc(g.status)}${g.network?` · ${esc(g.network)}`:''}</p></div><div class="focus-score">${teamLine(g.away)}${teamLine(g.home)}</div><div class="focus-meta"><span>${esc(g.venue||'Venue TBD')}</span><span>${new Date(g.date).toLocaleString()}</span></div><div class="button-row"><button class="button primary" data-game="${g.id}">Open details</button><button class="button" id="focusWeather">Load venue weather</button></div>`;$('focusBackdrop').classList.remove('hidden');if($('focusWeather'))$('focusWeather').onclick=()=>{settings.weatherLocation=[g.city,g.stateCode].filter(Boolean).join(', ');closeFocus();navigate('weather');fetchWeather(settings.weatherLocation)};$('focusBody').querySelector('[data-game]').onclick=()=>{closeFocus();showGame(g.id)}}
function closeFocus(){focusedGameId=null;$('focusBackdrop').classList.add('hidden')}
function notificationsPage(){const items=notificationHistory.length?notificationHistory.map(n=>`<button class="intel-row" data-alert-game="${esc(n.gameId)}"><span class="intel-icon">⚡</span><div><strong>${esc(n.title)}</strong><small>${esc(n.message)} · ${new Date(n.time).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</small></div></button>`).join(''):empty('No GameDay alerts yet','Score changes and favorite-team activity will appear here while the app is open.');return `<div class="notification-history">${items}</div>`}

function placeholderPage(id,label){setHeading(label,'COMING IN A PLANNED RELEASE');return `<div class="hero"><div class="hero-copy"><p class="eyebrow">ROADMAP MODULE</p><h2>${label}</h2><p>This route is prepared and will receive its full module in a future release.</p></div><img src="assets/onlybeats-icon.png"></div>`}
function toggle(id,label,on){return `<div class="toggle-row"><div><strong>${label}</strong></div><button id="${id}" class="toggle ${on?'on':''}"></button></div>`}
function settingsPage(){setHeading('Settings','LOCAL PREFERENCES');return `<div class="settings-layout"><section class="card settings-card"><h3>Appearance</h3><div class="field"><label>Theme</label><select id="themeSelect"><option value="dark">Dark Command Center</option><option value="light">Light</option></select></div>${toggle('compactToggle','Compact game cards',settings.compact)}${toggle('animationToggle','Interface animations',settings.animations)}</section><section class="card settings-card"><h3>GameDay alerts</h3>${toggle('scoreAlertsToggle','Score-change alerts',settings.scoreAlerts)}${toggle('favoriteAlertsToggle','Favorite-team alerts',settings.favoriteAlerts)}${toggle('kickoffAlertsToggle','Kickoff reminders',settings.kickoffAlerts)}</section><section class="card settings-card"><h3>Live scores</h3><div class="field"><label>Automatic refresh</label><select id="refreshSelect"><option value="15">15 seconds</option><option value="30">30 seconds</option><option value="60">60 seconds</option><option value="0">Off</option></select></div><button class="button primary" id="testProvider">Test live-score provider</button></section><section class="card settings-card"><h3>Startup</h3><div class="field"><label>Start page</label><select id="startPageSelect">${pages.map(([id,,l])=>`<option value="${id}">${l}</option>`).join('')}</select></div></section><section class="card settings-card"><h3>Data & recovery</h3><div class="button-row"><button id="exportButton" class="button primary">Export settings</button><button id="resetButton" class="button danger">Reset settings</button></div><p class="muted">App ${VERSION} · Database schema 1</p></section></div>`}
function renderPage(){const label=pages.find(p=>p[0]===currentPage)?.[2]||'Module';$('content').innerHTML=currentPage==='dashboard'?dashboard():currentPage==='wall'?wallPage():currentPage==='favorites'?favoritesPage():currentPage==='teams'?teamHubPage():currentPage==='rankings'?rankingsPage():currentPage==='news'?newsPage():currentPage==='weather'?weatherPage():currentPage==='developer'?developerPage():currentPage==='settings'?settingsPage():placeholderPage(currentPage,label);bindPage()}
function bindPage(){document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>showGame(b.dataset.game));document.querySelectorAll('[data-open-wall]').forEach(b=>b.onclick=()=>navigate('wall'));if($('refreshScores'))$('refreshScores').onclick=()=>syncScores();document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{wallState.status=b.dataset.status;saveWall();renderPage()});if($('favoritesFilter'))$('favoritesFilter').onclick=()=>{wallState.favoritesOnly=!wallState.favoritesOnly;saveWall();renderPage()};if($('top25Filter'))$('top25Filter').onclick=()=>{wallState.top25Only=!wallState.top25Only;saveWall();renderPage()};if($('wallSearch'))$('wallSearch').oninput=e=>{wallState.query=e.target.value;saveWall();const grid=document.querySelector('.wall-grid');if(grid)grid.innerHTML=filteredWallGames().map(gameCard).join('')||empty('No games match these filters','Try another team or clear filters.');document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>showGame(b.dataset.game))};document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{favorites=favorites.filter(x=>x!==b.dataset.remove);saveFavorites()});document.querySelectorAll('[data-team]').forEach(b=>b.onclick=()=>{activeTeamAbbr=b.dataset.team;teamTab='overview';renderPage()});document.querySelectorAll('[data-team-tab]').forEach(b=>b.onclick=()=>{teamTab=b.dataset.teamTab;renderPage()});if($('teamSearch'))$('teamSearch').oninput=e=>{teamQuery=e.target.value;renderPage();setTimeout(()=>{const x=$('teamSearch');if(x){x.focus();x.setSelectionRange(x.value.length,x.value.length)}},0)};if($('teamFavoriteButton'))$('teamFavoriteButton').onclick=()=>{const t=selectedTeam();if(!t)return;favorites=favorites.includes(t.abbr)?favorites.filter(x=>x!==t.abbr):[...favorites,t.abbr];localStorage.setItem(FAVORITES_KEY,JSON.stringify(favorites));renderPage()};if($('loadWeather'))$('loadWeather').onclick=()=>fetchWeather($('weatherLocation').value.trim());document.querySelectorAll('[data-focus]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();openFocus(b.dataset.focus)});document.querySelectorAll('[data-alert-game]').forEach(b=>b.onclick=()=>{const id=b.dataset.alertGame;if(id)showGame(id)});if(currentPage==='settings')bindSettings()}
function showGame(id,open=true){const g=games.find(x=>x.id===id);if(!g)return;activeGameId=id;const choices=[g.away,g.home];$('gameDrawerBody').innerHTML=`<div class="drawer-hero"><p class="eyebrow">${esc(statusLabel(g.state))}</p><h2>${esc(g.away.shortName)} at ${esc(g.home.shortName)}</h2><p>${esc(g.status)}</p></div><div class="drawer-score">${teamLine(g.away)}${teamLine(g.home)}</div><div class="drawer-details"><div><span>Broadcast</span><strong>${esc(g.network||'Not listed')}</strong></div><div><span>Venue</span><strong>${esc(g.venue||'Not listed')}</strong></div><div><span>Location</span><strong>${esc([g.city,g.stateCode].filter(Boolean).join(', ')||'Not listed')}</strong></div><div><span>Kickoff</span><strong>${new Date(g.date).toLocaleString()}</strong></div></div><div class="drawer-section"><h3>Favorite teams</h3><div class="button-row">${choices.map(t=>`<button class="button ${favorites.includes(t.abbr)?'primary':''}" data-favorite="${esc(t.abbr)}">${favorites.includes(t.abbr)?'★ Remove':'☆ Add'} ${esc(t.shortName)}</button>`).join('')}</div></div><div class="drawer-section"><h3>Team Hub</h3><div class="button-row">${choices.map(t=>`<button class="button" data-open-team="${esc(t.abbr)}">Open ${esc(t.shortName)}</button>`).join('')}</div></div><div class="drawer-section future-panel"><span>Coming next</span><p>Weather, team stats, possession, and play-by-play will plug into this drawer in future releases.</p></div>`;if(open){$('gameDrawerBackdrop').classList.remove('hidden');$('gameDrawer').classList.add('open')}document.querySelectorAll('[data-favorite]').forEach(b=>b.onclick=()=>{const a=b.dataset.favorite;favorites=favorites.includes(a)?favorites.filter(x=>x!==a):[...favorites,a];localStorage.setItem(FAVORITES_KEY,JSON.stringify(favorites));showGame(id,false);renderPage()});document.querySelectorAll('[data-open-team]').forEach(b=>b.onclick=()=>openTeam(b.dataset.openTeam))}
function closeGame(){activeGameId=null;$('gameDrawer').classList.remove('open');setTimeout(()=>$('gameDrawerBackdrop').classList.add('hidden'),180)}
function bindSettings(){const t=$('themeSelect');t.value=settings.theme;t.onchange=()=>{settings.theme=t.value;applyTheme();saveSettings()};const r=$('refreshSelect');r.value=settings.refresh;r.onchange=()=>{settings.refresh=r.value;saveSettings()};const s=$('startPageSelect');s.value=settings.startPage;s.onchange=()=>{settings.startPage=s.value;saveSettings()};[['compactToggle','compact'],['animationToggle','animations'],['scoreAlertsToggle','scoreAlerts'],['favoriteAlertsToggle','favoriteAlerts'],['kickoffAlertsToggle','kickoffAlerts']].forEach(([id,k])=>$(id).onclick=e=>{settings[k]=!settings[k];e.currentTarget.classList.toggle('on',settings[k]);applyTheme();saveSettings()});$('testProvider').onclick=()=>syncScores();$('exportButton').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({settings,favorites,wallState},null,2)],{type:'application/json'}));a.download='OnlyBeats-settings-v0.6.0.json';a.click();toast('Settings export created')};$('resetButton').onclick=()=>{if(confirm('Reset preferences, filters, and favorites?')){settings={...defaultSettings};favorites=[];wallState={...defaultWall};localStorage.clear();applyTheme();renderPage()}}}
const palette=$('commandPalette'),input=$('commandInput'),results=$('commandResults');
function openPalette(){palette.classList.remove('hidden');input.value='';renderCommands('');setTimeout(()=>input.focus(),0)}
function closePalette(){palette.classList.add('hidden')}
function renderCommands(q){const pageRows=pages.filter(p=>p[2].toLowerCase().includes(q.toLowerCase())).map(([id,i,l])=>`<button class="command-result" data-page="${id}"><span>${i} ${l}</span><small>Open page</small></button>`);const teamRows=allTeams().filter(t=>q&&`${t.name} ${t.abbr}`.toLowerCase().includes(q.toLowerCase())).slice(0,8).map(t=>`<button class="command-result" data-command-team="${esc(t.abbr)}"><span>◈ ${esc(t.name)}</span><small>Open Team Hub</small></button>`);results.innerHTML=[...pageRows,...teamRows].join('');results.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{navigate(b.dataset.page);closePalette()});results.querySelectorAll('[data-command-team]').forEach(b=>b.onclick=()=>{openTeam(b.dataset.commandTeam);closePalette()})}
$('commandButton').onclick=openPalette;palette.onclick=e=>{if(e.target===palette)closePalette()};input.oninput=()=>renderCommands(input.value);$('closeGameDrawer').onclick=closeGame;$('gameDrawerBackdrop').onclick=e=>{if(e.target.id==='gameDrawerBackdrop')closeGame()};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openPalette()}if(e.key==='Escape'){closePalette();closeGame()}});$('themeButton').onclick=()=>{settings.theme=settings.theme==='dark'?'light':'dark';applyTheme();saveSettings()};notificationHistory=load('onlybeats.notifications.v1',[]);$('notificationButton').onclick=()=>{const panel=$('notificationPanel');$('notificationList').innerHTML=notificationsPage();panel.classList.toggle('hidden')};$('closeNotifications').onclick=()=>$('notificationPanel').classList.add('hidden');$('closeFocus').onclick=closeFocus;$('focusBackdrop').onclick=e=>{if(e.target.id==='focusBackdrop')closeFocus()};setInterval(()=>{const c=$('clock');if(c)c.textContent=new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})},1000);
applyTheme();renderNav();renderPage();scheduleRefresh();const startupMessages=['Loading live scores…','Loading teams…','Preparing GameDay alerts…','Ready.'];let startupIndex=0;const startupTimer=setInterval(()=>{const el=$('splashStatus');if(el)el.textContent=startupMessages[startupIndex]||'Ready.';startupIndex++;if(startupIndex>=startupMessages.length){clearInterval(startupTimer);setTimeout(()=>$('splash').classList.add('hide'),300)}},380);syncScores(true);
